- mChi: 1
  mPhi: 100
  spin: pseudoscalar
  xsec: 0.2286
  xsec_unc: 0.00034
- mChi: 1
  mPhi: 10
  spin: pseudoscalar
  xsec: 0.5409
  xsec_unc: 0.00084
- mChi: 1
  mPhi: 150
  spin: pseudoscalar
  xsec: 0.1483
  xsec_unc: 0.00024
- mChi: 1
  mPhi: 200
  spin: pseudoscalar
  xsec: 0.09949
  xsec_unc: 0.00016
- mChi: 1
  mPhi: 250
  spin: pseudoscalar
  xsec: 0.06868
  xsec_unc: 0.00012
- mChi: 1
  mPhi: 300
  spin: pseudoscalar
  xsec: 0.04864
  xsec_unc: 9.1e-05
- mChi: 1
  mPhi: 350
  spin: pseudoscalar
  xsec: 0.02807
  xsec_unc: 5.4e-05
- mChi: 1
  mPhi: 400
  spin: pseudoscalar
  xsec: 0.0145
  xsec_unc: 2.8e-05
- mChi: 1
  mPhi: 450
  spin: pseudoscalar
  xsec: 0.009637
  xsec_unc: 2.1e-05
- mChi: 1
  mPhi: 500
  spin: pseudoscalar
  xsec: 0.006797
  xsec_unc: 1.3e-05
- mChi: 1
  mPhi: 50
  spin: pseudoscalar
  xsec: 0.3675
  xsec_unc: 0.00055
- mChi: 20
  mPhi: 100
  spin: pseudoscalar
  xsec: 0.2294
  xsec_unc: 0.00034
- mChi: 30
  mPhi: 100
  spin: pseudoscalar
  xsec: 0.229
  xsec_unc: 0.00034
- mChi: 40
  mPhi: 100
  spin: pseudoscalar
  xsec: 0.2296
  xsec_unc: 0.00034
- mChi: 45
  mPhi: 100
  spin: pseudoscalar
  xsec: 0.2296
  xsec_unc: 0.00036
- mChi: 49
  mPhi: 100
  spin: pseudoscalar
  xsec: 0.2303
  xsec_unc: 0.00035
- mChi: 51
  mPhi: 100
  spin: pseudoscalar
  xsec: 0.02103
  xsec_unc: 3.3e-05
- mChi: 55
  mPhi: 100
  spin: pseudoscalar
  xsec: 0.008131
  xsec_unc: 1.3e-05
- mChi: 1
  mPhi: 100
  spin: scalar
  xsec: 0.7906
  xsec_unc: 0.0012
- mChi: 1
  mPhi: 10
  spin: scalar
  xsec: 23.53
  xsec_unc: 0.034
- mChi: 1
  mPhi: 150
  spin: scalar
  xsec: 0.2561
  xsec_unc: 0.00036
- mChi: 1
  mPhi: 200
  spin: scalar
  xsec: 0.1074
  xsec_unc: 0.00015
- mChi: 1
  mPhi: 250
  spin: scalar
  xsec: 0.05633
  xsec_unc: 8.6e-05
- mChi: 1
  mPhi: 300
  spin: scalar
  xsec: 0.03465
  xsec_unc: 5.4e-05
- mChi: 1
  mPhi: 350
  spin: scalar
  xsec: 0.02358
  xsec_unc: 4.0e-05
- mChi: 1
  mPhi: 400
  spin: scalar
  xsec: 0.01447
  xsec_unc: 2.4e-05
- mChi: 1
  mPhi: 450
  spin: scalar
  xsec: 0.00934
  xsec_unc: 1.6e-05
- mChi: 1
  mPhi: 500
  spin: scalar
  xsec: 0.006406
  xsec_unc: 1.1e-05
- mChi: 1
  mPhi: 50
  spin: scalar
  xsec: 3.508
  xsec_unc: 0.0052
- mChi: 20
  mPhi: 100
  spin: scalar
  xsec: 0.7924
  xsec_unc: 0.0012
- mChi: 30
  mPhi: 100
  spin: scalar
  xsec: 0.7932
  xsec_unc: 0.0012
- mChi: 40
  mPhi: 100
  spin: scalar
  xsec: 0.8037
  xsec_unc: 0.0012
- mChi: 49
  mPhi: 100
  spin: scalar
  xsec: 0.8218
  xsec_unc: 0.0013
- mChi: 51
  mPhi: 100
  spin: scalar
  xsec: 0.009434
  xsec_unc: 1.4e-05
- mChi: 55
  mPhi: 100
  spin: scalar
  xsec: 0.00464
  xsec_unc: 6.5e-06
